// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CharityHub.Core.Domain.Entities;


public class CampaignCategory
{
    public int CampaignId { get; private set; }
    public Campaign Campaign { get; private set; }

    public int CategoryId { get; private set; }
    public Category Category { get; private set; }

}