// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using CharityHub.Core.Domain.ValueObjects;

using Microsoft.EntityFrameworkCore;

namespace CharityHub.Core.Domain.Entities;

public sealed class Campaign : BaseEntity
{
    public string Title {get; private set;}

    public string Description {get; private set;}

    public DateTime? StartDate {get; private set;}

    public DateTime? EndDate {get; private set;}

    public decimal? TotalAmount {get; private set;}

    public decimal? ChargedAmount {get; private set;}

    public string Photo {get; private set;}

    public int? CityId {get; private set;}

    public int CharityId {get; private set;}
    public Charity Charity {get; private set;}
    public ICollection<Donation> Donations {get; private set;} = new HashSet<Donation>();
}