// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using CharityHub.Core.Domain.ValueObjects;

using Microsoft.EntityFrameworkCore;

namespace CharityHub.Core.Domain.Entities;


public class Category : BaseEntity
{
    [StringLength(10)]
    public string Name { get; private set; }
}