// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CharityHub.Core.Domain.Entities;

using Microsoft.EntityFrameworkCore;

namespace CharityHub.Core.Domain.Entities;


public class CharityCategory
{
    public int CharityId {get; private set;}
    public virtual Category Category {get; private set;}


    public int CategoryId {get; private set;}
    public virtual Charity Charity {get; private set;}
}