// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using CharityHub.Core.Domain.Entities.Identity;
using CharityHub.Core.Domain.ValueObjects;

using Microsoft.EntityFrameworkCore;

namespace CharityHub.Core.Domain.Entities;


public class Charity : BaseEntity
{

    [StringLength(255)]
    public string Name {get; private set;}

    public string Description {get; private set;}

    [StringLength(255)]
    public string Website {get; private set;}

    public int CreatedByUserId {get; private set;}


    public string Address {get; private set;}

    public int? CityId {get; private set;}

    [StringLength(15)]
    [Unicode(false)]
    public string Telephone {get; private set;}

    [StringLength(50)]
    public string ManagerName {get; private set;}

    public int? SocialId {get; private set;}

    [StringLength(50)]
    public string ContactName {get; private set;}

    [StringLength(15)]
    [Unicode(false)]
    public string ContactPhoneNumber {get; private set;}

    public ICollection<Campaign> Campaigns {get; private set;} = new HashSet<Campaign>();

    public ApplicationUser CreatedByNavigation {get; private set;}
}